//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// (C) Copyright 2018-2025 Modeling Value Group B.V. (http://modelingvalue.org)                                        ~
//                                                                                                                     ~
// Licensed under the GNU Lesser General Public License v3.0 (the 'License'). You may not use this file except in      ~
// compliance with the License. You may obtain a copy of the License at: https://choosealicense.com/licenses/lgpl-3.0  ~
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on ~
// an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the  ~
// specific language governing permissions and limitations under the License.                                          ~
//                                                                                                                     ~
// Maintainers:                                                                                                        ~
//     Wim Bast, Tom Brus                                                                                              ~
//                                                                                                                     ~
// Contributors:                                                                                                       ~
//     Victor Lap                                                                                                      ~
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// This module contains JavaScript translations of Java source files
// The translations are generated by the translateToJs task

plugins {
    `java-library`
    id("org.teavm") version "0.10.2"
}

repositories {
    mavenCentral()
}

dependencies {
    // Reference the main project (brings in Nelumbo classes)
    implementation(project(":"))

    // Explicitly declare immutable-collections (same version as main project)
    // This is needed because Gradle doesn't expose transitive implementation dependencies
    implementation("org.modelingvalue:immutable-collections:4.1.0-BRANCHED")

    // TeaVM dependencies for browser integration
    implementation("org.teavm:teavm-core:0.10.2")
    implementation("org.teavm:teavm-jso:0.10.2")
    implementation("org.teavm:teavm-jso-apis:0.10.2")
    implementation("org.teavm:teavm-classlib:0.10.2")
}

// Configure TeaVM
teavm.js {
    mainClass = "org.modelingvalue.nelumbo.Main"
    addedToWebApp = false
}

// Alias task for TeaVM transpilation
tasks.register("translateToJs") {
    group = "translation"
    description = "Translates all Java source files to JavaScript using TeaVM"
    dependsOn("generateJavaScript")
}
