//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// (C) Copyright 2018-2026 Modeling Value Group B.V. (http://modelingvalue.org)                                        ~
//                                                                                                                     ~
// Licensed under the GNU Lesser General Public License v3.0 (the 'License'). You may not use this file except in      ~
// compliance with the License. You may obtain a copy of the License at: https://choosealicense.com/licenses/lgpl-3.0  ~
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on ~
// an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the  ~
// specific language governing permissions and limitations under the License.                                          ~
//                                                                                                                     ~
// Maintainers:                                                                                                        ~
//     Wim Bast, Tom Brus                                                                                              ~
//                                                                                                                     ~
// Contributors:                                                                                                       ~
//     Victor Lap                                                                                                      ~
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

plugins {
    java
    // TeaVM version is a module-unique literal (version-catalog convention: shared versions only)
    id("org.teavm") version "0.15.0"
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation(project(":"))
    // build-time-only: the ReflectionSupplier SPI the TeaVM compiler discovers via META-INF/services
    compileOnly("org.teavm:teavm-core:0.15.0")
}

// Embed the stdlib .nl sources as string constants: Class.getResource does not exist under TeaVM,
// so EmbeddedStdlibResolver serves imports from the generated StdlibSources map instead.
val stdlibModules = listOf("lang", "logic", "integers", "rationals", "strings", "collections", "datetime")
val generateStdlibSources = tasks.register("generateStdlibSources") {
    val resourceRoot = rootProject.layout.projectDirectory.dir("src/main/resources/org/modelingvalue/nelumbo")
    val outDir = layout.buildDirectory.dir("generated/stdlib")
    inputs.files(stdlibModules.map { resourceRoot.file("$it/$it.nl") })
    outputs.dir(outDir)
    doLast {
        fun escape(s: String) = s
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\r", "\\r")
            .replace("\t", "\\t")
            .replace("\n", "\\n")
        val entries = stdlibModules.joinToString(",\n") { module ->
            val text = resourceRoot.file("$module/$module.nl").asFile.readText()
            "            Map.entry(\"/org/modelingvalue/nelumbo/$module/$module.nl\", \"${escape(text)}\")"
        }
        val file = outDir.get().file("org/modelingvalue/nelumbo/browser/StdlibSources.java").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |package org.modelingvalue.nelumbo.browser;
            |
            |import java.util.Map;
            |
            |// GENERATED by :browser:generateStdlibSources from src/main/resources - do not edit
            |public final class StdlibSources {
            |
            |    private StdlibSources() {
            |    }
            |
            |    public static final Map<String, String> SOURCES = Map.ofEntries(
            |${entries}
            |    );
            |}
            |""".trimMargin()
        )
    }
}
sourceSets["main"].java.srcDir(generateStdlibSources)

// The TeaVM compiler must see this module's classes BEFORE the dependency jars, so the same-FQN
// overlay classes shadow the originals (javac already guarantees this for its own compilation).
tasks.named<org.teavm.gradle.tasks.GenerateJavaScriptTask>("generateJavaScript") {
    val original = classpath.from.toList()
    classpath.setFrom(listOf(sourceSets["main"].output) + original)
}

teavm.js {
    mainClass = "org.modelingvalue.nelumbo.browser.NelumboBrowser"
    moduleType = org.teavm.gradle.api.JSModuleType.UMD
    targetFileName = "nelumbo.js"
    obfuscated = true
    sourceMap = false
}
