//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// (C) Copyright 2018-2026 Modeling Value Group B.V. (http://modelingvalue.org)                                        ~
//                                                                                                                     ~
// Licensed under the GNU Lesser General Public License v3.0 (the 'License'). You may not use this file except in      ~
// compliance with the License. You may obtain a copy of the License at: https://choosealicense.com/licenses/lgpl-3.0  ~
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on ~
// an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the  ~
// specific language governing permissions and limitations under the License.                                          ~
//                                                                                                                     ~
// Maintainers:                                                                                                        ~
//     Wim Bast, Tom Brus                                                                                              ~
//                                                                                                                     ~
// Contributors:                                                                                                       ~
//     Victor Lap                                                                                                      ~
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

plugins {
    java
    // TeaVM version is a module-unique literal (version-catalog convention: shared versions only)
    id("org.teavm") version "0.15.0"
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation(project(":"))
    // build-time-only: the ReflectionSupplier SPI the TeaVM compiler discovers via META-INF/services
    compileOnly("org.teavm:teavm-core:0.15.0")
}

// Embed the stdlib .nl sources as string constants: Class.getResource does not exist under TeaVM,
// so EmbeddedStdlibResolver serves imports from the generated StdlibSources map instead.
val stdlibModules = listOf("lang", "logic", "integers", "rationals", "strings", "collections", "datetime")
val generateStdlibSources = tasks.register("generateStdlibSources") {
    val resourceRoot = rootProject.layout.projectDirectory.dir("src/main/resources/org/modelingvalue/nelumbo")
    val outDir = layout.buildDirectory.dir("generated/stdlib")
    inputs.files(stdlibModules.map { resourceRoot.file("$it/$it.nl") })
    outputs.dir(outDir)
    doLast {
        fun escape(s: String) = s
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\r", "\\r")
            .replace("\t", "\\t")
            .replace("\n", "\\n")
        val entries = stdlibModules.joinToString(",\n") { module ->
            val text = resourceRoot.file("$module/$module.nl").asFile.readText()
            "            Map.entry(\"/org/modelingvalue/nelumbo/$module/$module.nl\", \"${escape(text)}\")"
        }
        val file = outDir.get().file("org/modelingvalue/nelumbo/browser/StdlibSources.java").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |package org.modelingvalue.nelumbo.browser;
            |
            |import java.util.Map;
            |
            |// GENERATED by :browser:generateStdlibSources from src/main/resources - do not edit
            |public final class StdlibSources {
            |
            |    private StdlibSources() {
            |    }
            |
            |    public static final Map<String, String> SOURCES = Map.ofEntries(
            |${entries}
            |    );
            |}
            |""".trimMargin()
        )
    }
}
sourceSets["main"].java.srcDir(generateStdlibSources)

// The TeaVM compiler must see this module's classes BEFORE the dependency jars, so the same-FQN
// overlay classes shadow the originals (javac already guarantees this for its own compilation).
tasks.named<org.teavm.gradle.tasks.GenerateJavaScriptTask>("generateJavaScript") {
    val original = classpath.from.toList()
    classpath.setFrom(listOf(sourceSets["main"].output) + original)
}

// Resolve the node executable: the PATH first (CI/setup-node and normal shells), then nvm's node
// versions - same pattern as the website module's findNpm (a Gradle daemon started outside a login
// shell does not see nvm on the PATH).
fun findNode(): String {
    val isWindows = System.getProperty("os.name").lowercase().contains("win")
    val exe       = if (isWindows) "node.exe" else "node"
    val onPath    = System.getenv("PATH").orEmpty().split(File.pathSeparator)
            .map { File(it, exe) }
    val nvmDir    = File(System.getProperty("user.home"), ".nvm/versions/node")
    val inNvm     = (nvmDir.listFiles()?.filter { it.isDirectory } ?: emptyList())
            .sortedByDescending { it.lastModified() }
            .map { File(it, "bin/$exe") }
    return (onPath + inNvm).firstOrNull { it.canExecute() }?.absolutePath ?: exe
}

// Node smoke test: pins the compiled bundle's eval output to the JVM results (see smoke.js).
// Node is already a build prerequisite (the website module bundles its frontend with npm).
val browserSmokeTest = tasks.register<Exec>("browserSmokeTest") {
    dependsOn(tasks.named("generateJavaScript"))
    inputs.file(layout.buildDirectory.file("generated/teavm/js/nelumbo.js"))
    inputs.file("src/test/js/smoke.js")
    commandLine(
        findNode(), "src/test/js/smoke.js",
        layout.buildDirectory.file("generated/teavm/js/nelumbo.js").get().asFile.path,
        rootProject.file("src/main/resources/org/modelingvalue/nelumbo/examples/family.nl").path,
    )
}
tasks.named("check") {
    dependsOn(browserSmokeTest)
}

teavm.js {
    mainClass = "org.modelingvalue.nelumbo.browser.NelumboBrowser"
    moduleType = org.teavm.gradle.api.JSModuleType.UMD
    targetFileName = "nelumbo.js"
    obfuscated = true
    sourceMap = false
}
