//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// (C) Copyright 2018-2026 Modeling Value Group B.V. (http://modelingvalue.org)                                        ~
//                                                                                                                     ~
// Licensed under the GNU Lesser General Public License v3.0 (the 'License'). You may not use this file except in      ~
// compliance with the License. You may obtain a copy of the License at: https://choosealicense.com/licenses/lgpl-3.0  ~
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on ~
// an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the  ~
// specific language governing permissions and limitations under the License.                                          ~
//                                                                                                                     ~
// Maintainers:                                                                                                        ~
//     Wim Bast, Tom Brus                                                                                              ~
//                                                                                                                     ~
// Contributors:                                                                                                       ~
//     Victor Lap                                                                                                      ~
//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

defaultTasks("mvgCorrector", "test", "publish", "mvgTagger", "editorJar", "cliJar")

plugins {
    `java-library`
    `maven-publish`
    id("org.modelingvalue.gradle.mvgplugin") version "3.0.4"
    id("com.gradleup.shadow") version "9.6.1"
    idea
    eclipse
}

mvgcorrector {
    setHeaderUrl("file:docs/header-template.txt")
    // docs/site is generated by build-slides (reveal-js assets etc.); it is not our source and must
    // not be header/eol-corrected - a second gradle run would otherwise fail overwriting those files.
    addHeaderFileExclude(".*docs/site/.*")
    addEolFileExclude(".*docs/site/.*")
//    forceHeaderCorrection = true
}

dependencies {
    // api: immutable-collections types are part of the core public API, so consumers of the
    // root project get the (single) version from the catalog on their compile classpath
    api(libs.immutable.collections)
    implementation(libs.mvg.json)
    implementation("com.formdev:flatlaf:3.7.2")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks {
    register<ShadowJar>("editorJar") {
        description = "produce the jar for running the editor"
        archiveBaseName.set("nelumbo-ide")
        archiveClassifier.set("")
        manifest {
            attributes["Main-Class"] = "org.modelingvalue.nelumbo.tools.NelumboEditor"
        }
        from(sourceSets.main.get().output)
        configurations = listOf(project.configurations.runtimeClasspath.get())

        // Exclude signature files from signed dependencies to avoid SecurityException
        exclude("META-INF/*.SF", "META-INF/*.DSA", "META-INF/*.RSA")

        doFirst {
            // Clean only previous shadow jars; leave regular publication jars intact
            val libsDir = layout.buildDirectory.dir("libs")
            libsDir.get().asFile.listFiles()
                ?.filter { f -> f.isFile && (f.name.endsWith("-editor.jar") || f.name.contains("-editor-") || f.name.contains("-ide-")) }
                ?.forEach { it.delete() }
        }
    }

    // the cli jar (which includes the HTTP eval server) is built by the :cli module's cliJar task

    shadowJar {
        // Disable default shadowJar task; use editorJar instead
        enabled = false
    }
}

publishing {
    publications {
        create<MavenPublication>("nelumbo") {
            from(components["java"])
            // artifact(tasks.shadowJar)
        }
    }
}

tasks.register<Exec>("build-slides") {
    val docsDir = file("${project.projectDir}/docs").absolutePath
    val projectRoot = project.projectDir.absolutePath

    val dockerCandidateFile = file("/opt/local/bin/docker")
    executable = if (dockerCandidateFile.exists() && dockerCandidateFile.canExecute()) dockerCandidateFile.absolutePath else "docker"
    args(
        "run",
        "--rm",
        "-v", "$docsDir:/work",         // Mount docs at /work (build output goes to /work/site)
        "-v", "$projectRoot:/project",  // Mount project root so ../src/... is reachable from /work
        "-v", "${gradle.gradleUserHomeDir}/caches/pip:/root/.cache/pip",
        "-w", "/work",
        "python:3.12-alpine",
        "sh", "-lc",
        """
        ln -s /project/src ../src 2>/dev/null || true; \
        pip install -q --disable-pip-version-check --root-user-action=ignore mkslides 2>&1 | grep -v 'Created wheel' || true; \
        mkslides build NELUMBO.md
        cp nelumbo.svg site/assets
        """
    )
}

tasks.named<Delete>("clean") {
    delete(file("docs/site"))
    delete(rootProject.layout.buildDirectory)
    delete(file("cli/build"))
    delete(file("website/build"))
    delete(file("lsp/server/build"))
    delete(file("lsp/plugins/eclipse/build"))
    delete(file("lsp/plugins/intellij/build"))
}

tasks.test {
    dependsOn(":lsp:server:test")
    dependsOn(":cli:test")
    dependsOn(":website:test")
    dependsOn(":mcp:test")
    finalizedBy("allTestsReport")
}

// one aggregated HTML report over every test task in every project; runs
// automatically after './gradlew test' (the per-task report lines are then
// suppressed in favor of the single ALL-tests line). Gradle's own index.html
// only has per-run tabs ("Gradle Test Run :xxx") without an overall total, so
// doLast writes an overview.html with the totals from the junit XML results.
val allTestsReport = tasks.register<TestReport>("allTestsReport") {
    destinationDirectory = layout.buildDirectory.dir("reports/tests/all")
    val sources = mutableListOf<Triple<String, Provider<Directory>, Provider<Directory>>>()
    allprojects.forEach { p ->
        p.tasks.withType<Test>().forEach { t ->
            testResults.from(t)
            sources.add(Triple(t.path, t.reports.junitXml.outputLocation, t.reports.html.outputLocation))
        }
    }
    doLast {
        fun attr(tag: String, n: String) = Regex("$n=\"([^\"]+)\"").find(tag)?.groupValues?.get(1)
        var totTests = 0
        var totFail  = 0
        var totSkip  = 0
        var totTime  = 0.0
        val rows     = StringBuilder()
        sources.forEach { (taskPath, xmlDir, htmlDir) ->
            var tests = 0
            var fail  = 0
            var skip  = 0
            var time  = 0.0
            xmlDir.get().asFile.listFiles { f -> f.name.endsWith(".xml") }?.forEach { f ->
                val tag = Regex("<testsuite\\b[^>]*>").find(f.readText())?.value ?: return@forEach
                tests += (attr(tag, "tests") ?: "0").toInt()
                fail += (attr(tag, "failures") ?: "0").toInt() + (attr(tag, "errors") ?: "0").toInt()
                skip += (attr(tag, "skipped") ?: "0").toInt()
                time += (attr(tag, "time") ?: "0").toDouble()
            }
            if (tests == 0 && fail == 0 && skip == 0) {
                return@forEach // e.g. the plugin projects: no tests at all
            }
            totTests += tests
            totFail += fail
            totSkip += skip
            totTime += time
            val link = htmlDir.get().asFile.resolve("index.html").toPath().toUri()
            val cls = if (fail > 0) "bad" else "ok"
            rows.append("<tr><td><a href=\"$link\">$taskPath</a></td><td>$tests</td><td class=\"$cls\">$fail</td><td>$skip</td><td>${"%.1f".format(time)}s</td></tr>\n")
        }
        val verdict = if (totFail > 0) "<span class=\"bad\">$totFail FAILED</span>" else "<span class=\"ok\">all passed</span>"
        val tabs = destinationDirectory.get().asFile.resolve("index.html").toPath().toUri()
        val out = destinationDirectory.get().asFile.resolve("overview.html")
        out.writeText(
            """
            <!DOCTYPE html><html><head><meta charset="utf-8"><title>All tests overview</title><style>
            body{font-family:sans-serif;margin:2em} table{border-collapse:collapse;margin-top:1em}
            td,th{border:1px solid #ccc;padding:.4em .9em;text-align:right} td:first-child,th:first-child{text-align:left}
            tr.total{font-weight:bold;background:#f2f2f2} .ok{color:#2a7a2a} .bad{color:#c22222}
            </style></head><body>
            <h1>All tests: $totTests tests, $totSkip skipped (known bugs), $verdict</h1>
            <p><a href="$tabs">per-run details (Gradle tabs)</a></p>
            <table><tr><th>test task</th><th>tests</th><th>failures</th><th>skipped</th><th>duration</th></tr>
            $rows<tr class="total"><td>TOTAL</td><td>$totTests</td><td class="${if (totFail > 0) "bad" else "ok"}">$totFail</td><td>$totSkip</td><td>${"%.1f".format(totTime)}s</td></tr>
            </table></body></html>
            """.trimIndent()
        )
        println("ALL tests report: ${out.toPath().toUri()}")
    }
}

// make failing tests stand out in the (CI) log: a red banner per failure + a GitHub error annotation
allprojects {
    tasks.withType<Test>().configureEach {
        val taskPath   = path
        val htmlReport = reports.html.outputLocation
        addTestListener(object : TestListener {
            val red   = "\u001B[91m"
            val reset = "\u001B[0m"
            val bar   = "#".repeat(120)

            override fun beforeSuite(suite: TestDescriptor) {
            }

            override fun beforeTest(testDescriptor: TestDescriptor) {
            }

            override fun afterTest(desc: TestDescriptor, result: TestResult) {
                if (result.resultType == TestResult.ResultType.FAILURE) {
                    val name = "${desc.className}.${desc.name}"
                    val msg  = result.exception?.toString() ?: "no exception info"
                    println()
                    println("$red$bar")
                    println("##")
                    println("##  TEST FAILED: $name")
                    msg.lines().forEach { println("##      $it") }
                    println("##")
                    println("$bar$reset")
                    println()
                    if (System.getenv("GITHUB_ACTIONS") != null) {
                        val oneLine = "$name: $msg".replace("%", "%25").replace("\r", "%0D").replace("\n", "%0A")
                        println("::error title=Test failed::$oneLine")
                    }
                }
            }

            override fun afterSuite(suite: TestDescriptor, result: TestResult) {
                if (suite.parent == null) {
                    if (result.failedTestCount > 0) {
                        println("$red$bar")
                        println("##  ${result.failedTestCount} FAILED test(s) in $taskPath - look for 'TEST FAILED' banners above")
                        println("$bar$reset")
                    }
                    if (!gradle.taskGraph.hasTask(":allTestsReport")) {
                        println("$taskPath report: ${htmlReport.get().asFile.resolve("index.html").toPath().toUri()}")
                    }
                }
            }
        })
    }
}
