nelumbo = namespace (typeDecl | functor | variable | rule)*;

namespace = H? qualified (H? ':' V? H? qualified (H? ',' V? H? qualified)*)? V;
typeDecl = H? identifier (H? ':' V? H? type (H? ',' V? H? type)*)? V;
functor = H? type H identifier H? '(' V?  (H? type (H? ',' V? H? type)*)? H? ')' V;
variable = H? type H identifier V;
rule = expression V;

type = identifier; 
expression = binaryOperatorCall;
binaryOperatorCall = unaryOperatorCall (H? operator V? H? binaryOperatorCall)?;
unaryOperatorCall = H? (operator H? unaryOperatorCall | primaryExpression);

primaryExpression = H? (literal | variableCall | bracketed | functorCall);
functorCall = identifier H? '(' V? (expression (H? ',' V? expression)*)? H? ')';
bracketed = '(' V? expression H? ')';
variableCall = identifier;
literal = number | decimal | string;

qualified = identifier ('.' identifier)+;
decimal = number '.' number;
number = /[0-9]+/;
string = '"' /[^"]*/ '"';
identifier = /[a-zA-Z_][a-zA-Z0-9_]*/;
operator = /[~!@#$%^&*\/\?|+-<>]+/;

H = /\h+/;
V = /(\h*(\/\/[^\v+]*)?\v+)+/;